package com.farmaciassss.views.modificarpedido;

import com.farmaciassss.views.MainLayout;
import com.vaadin.flow.component.Composite;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.button.ButtonVariant;
import com.vaadin.flow.component.datepicker.DatePicker;
import com.vaadin.flow.component.dependency.Uses;
import com.vaadin.flow.component.html.H1;
import com.vaadin.flow.component.html.H2;
import com.vaadin.flow.component.html.H3;
import com.vaadin.flow.component.icon.Icon;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.theme.lumo.LumoUtility.Gap;

@PageTitle("Modificar Pedido")
@Route(value = "modificar-pedido", layout = MainLayout.class)
@Uses(Icon.class)
public class ModificarPedidoView extends Composite<VerticalLayout> {

    public ModificarPedidoView() {
        HorizontalLayout layoutRow = new HorizontalLayout();
        VerticalLayout layoutColumn2 = new VerticalLayout();
        H1 h1 = new H1();
        TextField textField = new TextField();
        Button buttonPrimary = new Button();
        TextField textField2 = new TextField();
        TextField textField3 = new TextField();
        TextField textField4 = new TextField();
        DatePicker datePicker = new DatePicker();
        HorizontalLayout layoutRow2 = new HorizontalLayout();
        Button buttonPrimary2 = new Button();
        Button buttonSecondary = new Button();
        VerticalLayout layoutColumn3 = new VerticalLayout();
        H2 h2 = new H2();
        H3 h3 = new H3();
        H2 h22 = new H2();
        H3 h32 = new H3();
        H2 h23 = new H2();
        getContent().setWidth("100%");
        getContent().getStyle().set("flex-grow", "1");
        layoutRow.setWidthFull();
        getContent().setFlexGrow(1.0, layoutRow);
        layoutRow.addClassName(Gap.MEDIUM);
        layoutRow.setWidth("100%");
        layoutRow.getStyle().set("flex-grow", "1");
        layoutColumn2.setHeightFull();
        layoutRow.setFlexGrow(1.0, layoutColumn2);
        layoutColumn2.setWidth("565px");
        layoutColumn2.getStyle().set("flex-grow", "1");
        h1.setText("Modificar Pedido");
        h1.setWidth("max-content");
        textField.setLabel("Numero del pedido");
        textField.setWidth("min-content");
        buttonPrimary.setText("Buscar");
        buttonPrimary.setWidth("min-content");
        buttonPrimary.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        textField2.setLabel("Nombre del Proveedor");
        textField2.setWidth("min-content");
        textField3.setLabel("Producto");
        textField3.setWidth("min-content");
        textField4.setLabel("Cantidad de Productos");
        textField4.setWidth("min-content");
        datePicker.setLabel("Fecha");
        datePicker.setWidth("min-content");
        layoutRow2.setWidthFull();
        layoutColumn2.setFlexGrow(1.0, layoutRow2);
        layoutRow2.addClassName(Gap.MEDIUM);
        layoutRow2.setWidth("100%");
        layoutRow2.getStyle().set("flex-grow", "1");
        buttonPrimary2.setText("Modificar");
        buttonPrimary2.setWidth("min-content");
        buttonPrimary2.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        buttonSecondary.setText("Cancelar");
        buttonSecondary.setWidth("min-content");
        layoutColumn3.setHeightFull();
        layoutRow.setFlexGrow(1.0, layoutColumn3);
        layoutColumn3.setWidth("100%");
        layoutColumn3.getStyle().set("flex-grow", "1");
        h2.setText("Numero del pedido");
        h2.setWidth("max-content");
        h3.setText("Heading");
        h3.setWidth("max-content");
        h22.setText("Estado del pedido");
        h22.setWidth("max-content");
        h32.setText("Heading");
        h32.setWidth("max-content");
        h23.setText("Detalles");
        h23.setWidth("max-content");
        getContent().add(layoutRow);
        layoutRow.add(layoutColumn2);
        layoutColumn2.add(h1);
        layoutColumn2.add(textField);
        layoutColumn2.add(buttonPrimary);
        layoutColumn2.add(textField2);
        layoutColumn2.add(textField3);
        layoutColumn2.add(textField4);
        layoutColumn2.add(datePicker);
        layoutColumn2.add(layoutRow2);
        layoutRow2.add(buttonPrimary2);
        layoutRow2.add(buttonSecondary);
        layoutRow.add(layoutColumn3);
        layoutColumn3.add(h2);
        layoutColumn3.add(h3);
        layoutColumn3.add(h22);
        layoutColumn3.add(h32);
        layoutColumn3.add(h23);
    }
}
